name: Jaehan Kim
# tagline: Electrical and Electronic Engineer
career-objective: ..
color-theme: red # red or blue
avatar-filename: photo.jpg # Change to your avatar's filename
url: jaehanwork.github.io
baseurl: /
# paginate: 5
# paginate_path: "/blog/page:num/"

# Social Information
social:
  email: 
    visibility: true
    mail: jaehan@kaist.ac.kr
  github: 
    visibility: true
    handle: jaehanwork
  linkedin: 
    visibility: true
    handle: jaehan-kim-1babb0252
  cv:
    visibility: true
    handle: /CV_Jaehan.pdf

# Collections
collections:
  experience:
    output: false
    sort_by: order
  education:
    output: false
    sort_by: order
  awards:
    output: false
    sort_by: order
  publications:
    output: true
    sort_by: year

# Home Page Options
collection_option:
  experience: 
    label: Experience
    visibility: true
  education: 
    label: Education
    visibility: true
  awards: 
    label: Awards
    visibility: true

navigation:
- title: Home
  url: /
- title: Publications
  url: /publications
# - title: Contact
#   url: /contact

include:
  - _pages

exclude:
  - readme.md

# Defaults
defaults:
  - scope:
      path: ''
      type: publications
    values:
      permalink: /publications/:title
      layout: publication
      comments: false

# Disqus Comment
disqus:
  shortname: academic-portfolio # Change with your own disqus shortname

# Contact Form
formspree:
  endpoint: https://formspree.io/f/xdorkgkv # Change with your own form's endpoint

# Google Analytics
google_analytics: UA—XXXXXXXX-X